# Generated by Django 5.1.1 on 2024-09-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_following_alter_customuser_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='following',
            new_name='followings',
        ),
    ]
