# Generated by Django 5.1.1 on 2024-09-29 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_following_customuser_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='followings',
            new_name='following',
        ),
    ]
