all:
	python3 manage.py makemigrations
	python3 manage.py migrate
	python3 manage.py runserver
server:
	python3 manage.py runserver
migrations:
	python3 manage.py makemigrations
	python3 manage.py migrate
superuser:
	python3 manage.py createsuperuser
